### ISSUE TITLE
Modules manquant après npm install -g

### ISSUE THREAD

**Issue by GBO** [wmoulin/joobster#3]
Bonjour mon bon,

Après une install (npm install -g), une compilation d'un projet PTS échoue : 
La commande qui échoue est la suivante : "jsr compile:js"
J'ai des erreurs modules pour au moins 2 modules (mais il doit y en avoir 4 voire plus) :
- config-chain (non présent PC témoin (VPD))
- gul-inject-string (présent sur un PC témoin (VPD))

Tchuss !

**Comment by wmoulin** [comment]
j'ai supprimé la référence à "gulp-inject-string" (un truc qui traînait désolé), j'ai fait une réinstallation complète et pas de souci. Donc soit sa vient du projet PTS soit d'une dépendance buggée.
Deux solutions, soit supprimer le cache npm et tout réinstaller, soit me dire sur quel projet que je regarde.
